language: csharp
mono: none
dotnet: 3.1.101
dist: xenial

notifications:
  email:
    - on_success: never
    - on_failure: always

services:
  - postgresql

env:
  - ConnectionStrings__DSJTournamentsDB="Host=localhost;Username=postgres;Database=dsjtournaments_test;Enlist=true"

script:
  - dotnet restore
  - dotnet build
  - find . -type d -name '*.*Tests' -exec dotnet test --no-restore --no-build {} ';'
