language: csharp
mono: none
dotnet: 2.0.0
dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - ConnectionStrings__DSJTournamentsDB="Host=localhost;Username=postgres;Database=dsjtournaments_test;Enlist=true"

script:
  - dotnet restore
  - dotnet build
  - find . -type d -name '*.*Tests' -exec dotnet test --no-restore --no-build {} ';'