-- Tournament Types
INSERT INTO tournament_types (id, name, game_version) VALUES (1, 'World Cup', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (2, '10th Anniversary Tournament', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (3, 'Tour de DSJ 2008', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (4, 'Tour de DSJ 2009', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (5, 'Tour de DSJ 2010', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (6, 'Tour de DSJ 2011', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (7, 'Marathon', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (8, 'World Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (9, 'World Cup A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (10, 'World Cup B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (11, 'Marathon A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (12, 'Marathon B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (13, 'Ski Flying A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (14, 'Ski Flying B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (15, 'Team Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (16, 'Tour de DSJ 2013', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (17, 'Tour de DSJ 2014', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (18, 'Tour de DSJ 2015', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (19, 'Tour de DSJ 2016', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (20, 'Tour de DSJ 2017', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (21, 'National Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (22, 'Tour de DSJ 2018', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (23, 'Tour de DSJ 2019', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (24, '20th Anniversary Tournament', 4);

-- Hills
INSERT INTO hills (id, name, nation, game_version) VALUES (3, 'Germany HS261', 'GER', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (4, 'China HS252', 'CHN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (5, 'United States HS171', 'USA', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (6, 'Croatia HS278', 'CRO', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (7, 'Bulgaria HS258', 'BGR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (8, 'Russia HS223', 'RUS', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (9, 'The Netherlands HS100', 'NED', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (10, 'Austria HS197', 'AUT', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (11, 'Latvia HS80', 'LVA', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (12, 'United Kingdom HS85', 'GBR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (13, 'Argentina HS240', 'ARG', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (14, 'Serbia HS69', 'SRB', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (15, 'Korea HS174', 'KOR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (16, 'Turkey HS177', 'TUR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (17, 'Lithuania HS153', 'LTU', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (18, 'Hungary HS117', 'HUN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (19, 'Georgia HS207', 'GEO', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (20, 'Czech Republic HS192', 'CZE', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (21, 'Canada HS107', 'CAN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (22, 'Iceland HS275', 'ISL', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (23, 'Slovenia HS281', 'SLO', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (24, 'Estonia HS185', 'EST', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (25, 'Belgium HS126', 'BEL', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (26, 'Belarus HS214', 'BLR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (27, 'Spain HS242', 'ESP', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (28, 'Bosnia and Herzegovina HS111', 'BIH', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (29, 'Sweden HS121', 'SWE', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (30, 'Slovakia HS180', 'SVK', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (31, 'Japan HS248', 'JPN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (32, 'Ukraine HS203', 'UKR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (33, 'Switzerland HS157', 'SUI', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (34, 'Finland HS218', 'FIN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (35, 'Norway HS138', 'NOR', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (36, 'Kazakhstan HS164', 'KAZ', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (37, 'Italy HS146', 'ITA', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (38, 'Australia HS149', 'AUS', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (39, 'France HS235', 'FRA', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (40, 'Denmark HS93', 'DEN', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (41, 'Romania HS228', 'ROU', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (42, 'Poland HS269', 'POL', 3);
INSERT INTO hills (id, name, nation, game_version) VALUES (1, 'Lillehammer HS138', 'NOR', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (2, 'Bad Mitterndorf HS200', 'AUT', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (43, 'Lahti HS130', 'FIN', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (44, 'Zakopane HS94', 'POL', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (45, 'Garmisch-Partenkirchen HS140', 'GER', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (46, 'Kuusamo HS142', 'FIN', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (48, 'Sapporo HS134', 'JPN', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (47, 'Planica HS215', 'SLO', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (49, 'Oberstdorf HS213', 'GER', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (50, 'Villach HS98', 'AUT', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (51, 'Engelberg HS137', 'SUI', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (53, 'Kuopio HS127', 'FIN', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (54, 'Lillehammer HS100', 'NOR', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (55, 'Val di Fiemme HS106', 'ITA', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (56, 'Val di Fiemme HS134', 'ITA', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (57, 'Willingen HS145', 'GER', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (58, 'Zakopane HS134', 'POL', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (59, 'Bischofshofen HS140', 'AUT', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (60, 'Harrachov HS205', 'CZE', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (61, 'Bischofshofen HS78', 'AUT', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (62, 'Klingenthal HS140', 'GER', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (65, 'Wisła HS134', 'POL', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (63, 'Park City HS100', 'USA', 4);
INSERT INTO hills (id, name, nation, game_version) VALUES (64, 'Park City HS134', 'USA', 4);

-- User
INSERT INTO users (username, password_hash) VALUES ('admin', 'AQAAAAEAACcQAAAAECcju8UqdRBp09Qck0C1h/u91NEk3aCcK+qupOZlevBZCe55QnoDwZPEg8nIqBNQAw==');