-- Tournament Types
INSERT INTO tournament_types (id, name, game_version) VALUES (1, 'World Cup', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (2, '10th Anniversary Tournament', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (3, 'Tour de DSJ 2008', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (4, 'Tour de DSJ 2009', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (5, 'Tour de DSJ 2010', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (6, 'Tour de DSJ 2011', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (7, 'Marathon', 3);
INSERT INTO tournament_types (id, name, game_version) VALUES (8, 'World Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (9, 'World Cup A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (10, 'World Cup B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (11, 'Marathon A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (12, 'Marathon B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (13, 'Ski Flying A', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (14, 'Ski Flying B', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (15, 'Team Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (16, 'Tour de DSJ 2013', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (17, 'Tour de DSJ 2014', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (18, 'Tour de DSJ 2015', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (19, 'Tour de DSJ 2016', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (20, 'Tour de DSJ 2017', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (21, 'National Cup', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (22, 'Tour de DSJ 2018', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (23, 'Tour de DSJ 2019', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (24, '20th Anniversary Tournament', 4);
INSERT INTO tournament_types (id, name, game_version) VALUES (25, 'Tour de DSJ 2020', 4);

-- Hills
INSERT INTO hills (name, nation, game_version) VALUES ('Germany HS261', 'GER', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('China HS252', 'CHN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('United States HS171', 'USA', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Croatia HS278', 'CRO', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Bulgaria HS258', 'BGR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Russia HS223', 'RUS', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('The Netherlands HS100', 'NED', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Austria HS197', 'AUT', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Latvia HS80', 'LVA', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('United Kingdom HS85', 'GBR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Argentina HS240', 'ARG', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Serbia HS69', 'SRB', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Korea HS174', 'KOR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Turkey HS177', 'TUR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Lithuania HS153', 'LTU', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Hungary HS117', 'HUN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Georgia HS207', 'GEO', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Czech Republic HS192', 'CZE', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Canada HS107', 'CAN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Iceland HS275', 'ISL', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Slovenia HS281', 'SLO', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Estonia HS185', 'EST', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Belgium HS126', 'BEL', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Belarus HS214', 'BLR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Spain HS242', 'ESP', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Bosnia and Herzegovina HS111', 'BIH', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Sweden HS121', 'SWE', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Slovakia HS180', 'SVK', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Japan HS248', 'JPN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Ukraine HS203', 'UKR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Switzerland HS157', 'SUI', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Finland HS218', 'FIN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Norway HS138', 'NOR', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Kazakhstan HS164', 'KAZ', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Italy HS146', 'ITA', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Australia HS149', 'AUS', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('France HS235', 'FRA', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Denmark HS93', 'DEN', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Romania HS228', 'ROU', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Poland HS269', 'POL', 3);
INSERT INTO hills (name, nation, game_version) VALUES ('Lillehammer HS138', 'NOR', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Bad Mitterndorf HS200', 'AUT', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Lahti HS130', 'FIN', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Zakopane HS94', 'POL', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Garmisch-Partenkirchen HS140', 'GER', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Kuusamo HS142', 'FIN', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Sapporo HS134', 'JPN', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Planica HS215', 'SLO', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Oberstdorf HS213', 'GER', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Villach HS98', 'AUT', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Engelberg HS137', 'SUI', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Kuopio HS127', 'FIN', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Lillehammer HS100', 'NOR', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Val di Fiemme HS106', 'ITA', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Val di Fiemme HS134', 'ITA', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Willingen HS145', 'GER', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Zakopane HS134', 'POL', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Bischofshofen HS140', 'AUT', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Harrachov HS205', 'CZE', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Bischofshofen HS78', 'AUT', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Klingenthal HS140', 'GER', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Wisła HS134', 'POL', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Park City HS100', 'USA', 4);
INSERT INTO hills (name, nation, game_version) VALUES ('Park City HS134', 'USA', 4);

-- User
INSERT INTO users (username, password_hash) VALUES ('admin', 'AQAAAAEAACcQAAAAECcju8UqdRBp09Qck0C1h/u91NEk3aCcK+qupOZlevBZCe55QnoDwZPEg8nIqBNQAw==');
