name: Deploy .NET Application via SSH

on:
  workflow_dispatch:

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    environment: linode

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish
      run: dotnet publish api/DSJTournaments.Api -c Release -r linux-x64 --self-contained -o dist/api

    - name: Pre-deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo mkdir -p /opt/dsjtournaments/api
            sudo rm -r /opt/dsjtournaments/api/*
    
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        strip_components: 2
        source: "dist/api/*"
        target: "/opt/dsjtournaments/api"
        
    - name: Post-deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo chown -R dsjtournaments:dsjtournaments /opt/dsjtournaments/api
          sudo chmod +x /opt/dsjtournaments/api/DSJTournaments.Api
          sudo systemctl restart dsjtournaments-api.service
